{{- if .Values.googleCredentials.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guhatek-onegt.credentialsSecretName" . }}
  labels:
    {{- include "guhatek-onegt.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ .Values.googleCredentials.credentialsBase64 | quote }}
{{- end }}
